build:
  environment:
    node: v20.10.0

  cache:
    directories:
      - bike/node_modules
      - api/node_modules

  dependencies:
    override:
      - cd bike && npm install
      - cd api && npm install

  tests:
    override:
      - cd bike && npm test -- --ci --coverage
      - cd api && npm test -- --ci --coverage
