build:
  nodes:
    node22:
      container:
        image: node:22

      dependencies:
        override:
          - node -v
          - npm -v
          - cd bike && npm ci
          - cd api && npm ci

      tests:
        override:
          - cd bike && npm test -- --ci --coverage
          - cd api && npm test -- --ci --coverage
